apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: weave-net
  name: weave-net
  namespace: kube-system
secrets:
  - name: weave-net-token-s55nh

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    name: weave-net
  name: weave-net
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - weave-net
    resources:
      - configmaps
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: weave-net
  name: weave-net
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: weave-net
subjects:
  - kind: ServiceAccount
    name: weave-net
    namespace: kube-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: weave-net
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: weave-net
  name: weave-net
  namespace: kube-system
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: weave-net
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]'
      labels:
        name: weave-net
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: NotIn
                    values:
                      - windows
      containers:
        - command:
            - /home/weave/launch.sh
          env:
            - name: INIT_CONTAINER
              value: "true"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: IPALLOC_RANGE
              value: 10.42.0.0/16
            - name: WEAVE_MTU
              value: "8939"
            - name: DB_PREFIX
              value: /weavedb/weave-net2
          image: et-dtr.artifactory.blueorigin.com/weaveworks/weave-kube:2.8.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ./weave --local status connections | awk '{print $4}' | grep fastdp
            failureThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          name: weave
          readinessProbe:
            failureThreshold: 3
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 6784
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 50m
          securityContext:
            privileged: true
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /weavedb
              name: weavedb
            - mountPath: /host/var/lib/dbus
              name: dbus
              readOnly: true
            - mountPath: /host/etc/machine-id
              name: cni-machine-id
              readOnly: true
            - mountPath: /run/xtables.lock
              name: xtables-lock
        - env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: DB_PREFIX
              value: /weavedb/weave-net2
          image: et-dtr.artifactory.blueorigin.com/weaveworks/weave-npc:2.8.1
          imagePullPolicy: IfNotPresent
          name: weave-npc
          resources:
            requests:
              cpu: 50m
          securityContext:
            privileged: true
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/xtables.lock
              name: xtables-lock
        - command:
            - /opt/rke-tools/weave-plugins-cni.sh
          image: et-dtr.artifactory.blueorigin.com/rancher/rke-tools:v0.1.80
          imagePullPolicy: IfNotPresent
          name: weave-plugins
          resources: {}
          securityContext:
            privileged: true
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt
              name: cni-bin
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
        - command:
            - /home/weave/init.sh
          image: et-dtr.artifactory.blueorigin.com/weaveworks/weave-kube:2.8.1
          imagePullPolicy: IfNotPresent
          name: weave-init
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /host/opt
              name: cni-bin
            - mountPath: /host/home
              name: cni-bin2
            - mountPath: /host/etc
              name: cni-conf
            - mountPath: /lib/modules
              name: lib-modules
            - mountPath: /run/xtables.lock
              name: xtables-lock
      priorityClassName: networking-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seLinuxOptions: {}
      serviceAccount: weave-net
      serviceAccountName: weave-net
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/weave
            type: ""
          name: weavedb
        - hostPath:
            path: /opt
            type: ""
          name: cni-bin
        - hostPath:
            path: /home
            type: ""
          name: cni-bin2
        - hostPath:
            path: /etc
            type: ""
          name: cni-conf
        - hostPath:
            path: /etc/machine-id
            type: ""
          name: cni-machine-id
        - hostPath:
            path: /var/lib/dbus
            type: ""
          name: dbus
        - hostPath:
            path: /lib/modules
            type: ""
          name: lib-modules
        - hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
          name: xtables-lock
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
